ALTER TABLE t_p84565078_code_expression_proj.courses
  ADD COLUMN IF NOT EXISTS type VARCHAR(20) NOT NULL DEFAULT 'online',
  ADD COLUMN IF NOT EXISTS event_date DATE NULL,
  ADD COLUMN IF NOT EXISTS event_time_start TIME NULL,
  ADD COLUMN IF NOT EXISTS event_time_end TIME NULL,
  ADD COLUMN IF NOT EXISTS event_location TEXT NULL,
  ADD COLUMN IF NOT EXISTS schedule JSONB NOT NULL DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS energy_reward INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS max_participants INTEGER NULL;
